#+title: Hero Twins
* The hero twins v.s. the great pretenders
** Seven Macaw
*** 1: Hunahpu and Xbalanque are two twin gods and heros to the quinche people
*** They are an example of the Hero Twins of the north and south americas
*** 2: They hear someone spreading some absolute bullshit
*** There is a god named =Seven Mcaw= and he is going around bragging about how great he is
**** His teeth are incrusted with glittering jewels, so bright that he claims he is the sun and the moon, providing light to the (flooded) humanity
***** While there is the sun-moon in the sky, it's clouded over
**** ="I am great. My place is now higher than that of the human work, human design. I am their sun and I am their light, and I am also their months".=
**** Now these are some fake shit
*** Now Hanapu and Xbalanque can't be having that, they are good boys
*** 3: The boys find him eating in his tree and try to kill him with a blowgun, shooting him in the jaw and shattering his teeth
*** This, rightly, pisses him the hell off
*** So in the ensuing fight, he ends up rips off Hanahpu's arm and takes it home
*** 4: Hunahpu and Xbalanque go home and their grandparents are shocked to see him missing a whole ass arm
*** As any grandparents would, they decide to go deal with Seven Macaw themselves
*** 5: At home, Seven Mcaw in pain, teeth loose and jaw broken, he needs a dentist
*** 6: Seven Macaw is visited by the grandparents, who offer to help ease his pain. They brought two young boys who seem a little familiar...
*** Seven Macaw Agrees to the DIY dentistry, and they replace his jeweled teeth with maize kernels and remove all of his piercings from his face
*** When theyre done, he looks in the mirror and, heart broken, he just drops dead
**** What a drama queen
** Xipacna
*** One day, the gods of alcoholic drink who have the best name: The Four Hundred Boys, asked Seven Macaw's eldest son, A Crocodile-shaped god Xipacna, to help them build a house
**** You'd think 400 boys could do it, but I'm guessing they were to busy partying
*** As Xipacna worked, they were also shocked at how proud and arrogant he was too, so the four hundred boys decide to kill him
*** The plan backfires, and Xipacna ends up knocking down the house kill the fourhundred boys!
**** That monster!
*** Hunahpu and Xbalanque hear about this and they create fake and delicious looking crab, tucking it in a crevice in a canyon
*** They go to Xipacna and tell him what a great and tasty looking crab they found, but they weren't nearly as /amazing/ and /awesome/ as xipacna so they couldn't catch it
*** Xipacna just so happened to be starving, so he went to the canyon, found the cave, and gets stuck in the crevice. Eventualy, he turns to stone, dying
** Earthquake
*** This time, Hunahpu and Xipacna are visited by Hurricane, Newborn Thunderbolt, and Sudden Thunderbolt (Heart of Sky) and tell him Sevemn Macaw's youngest son is going around bragging about how great /he/ is, how he's even /better/ than the sun
*** The boys convince him to travel with them, and along the way they make a delicious smelling meal of some birds they hunted.
*** Unbeknowst to Earthquake, this is a dinner most /fowl/ and one of the birds is coated with gypsum. He eats the bird, and he Gypsum hardens inside him, paralyzing him so the boys can bury him.
** With that, the boys have helped prepare earth for the coming of the successful human race......
*** WAIT, I DIDN'T EXPLAIN WHERE THEY COME FROM
* One Hunahpu and Seven Hunahpu in Xibalba
** Yes, you heard that right. Let me explain
** One Hunahpu an Seven Hunahpu are twins and two of the parents of Hunahpu and Xibalanque.
*** Yes, I said /two/ of the parents. This will make sense soon
** The lords of Xibalba, the lords of death live deep below the ground
*** Flying Scab
*** Blood Gatherer
*** Pus Demon
*** Jaundice Demon
*** Bone Staff
*** Skull Staff
*** Sweepings Demon
*** Stabbing Demon
*** Blood Moon
** The two brothers, One Hunahpu and Seven Hunahpu are being /too loud/ and so they invite them to come play in Xibalba
** Xmucane weeps because she knows this will mean their deaths
** One Hunahpu and Seven Hunahpu go on an ardous journey, suffering many defeatsd
** When they arrive, they underwent tests in the Dark House, tricked by the Lords of Xibalba, they are killed

** They are buried together except for One Hunahpu's head, who's put in a fruit tree on the side of the road as a trophy
** Blood Gatherer mentions this tree to his daughter, Blood Moon, and she decides to visit the tree
** When she reaches to pick the fruit, One Hunahpu spits on her hand, telling her in the voice of One Hunahpu and Seven Hunahpu that he and his brother will /live on in you/
*** yes, this is how she gets impregnated by /both/ One Hunahpu and Seven Hunahou
** When her father sees her pregnant, he orders his servants to kill her. They spare her, and she flees to the surface
** Offscreen Egret Woman dies, no one knows why
** Xmucane is taking care of her grandchildren One Monkey and One Artisan when Blood Moon shows up, claiming she is pregnant with One Hunahpu and Seven Hunahpu's sons
** She doesn't believe her at first, but after she proves it by succeeding in producing infinite Maize from a single ear, she accepts it as proof
** The brothers grow up, Blood Moon also dies off-screen, and One Monkey and One Artisan are jealous of their half-brothers think theyre great and fuck with them
** Their grandma supports them
** The brothers, as we know, don't take shit from nobody, and trick them into climbing a tree where they are transformed into monkeys
** Like fathers like sons, they play ball and cause a ruckus, causing the Lords of death to invite them to play again
** Xmucane knows they will die there, but they plant corn for her and tell her that they will grow and die as they do
** On the way there, the twins send a mosquito to scout ahead of them, and using the mosquito's information they avoid all of the traps on the journey
** In the Dark House, they are put through the same tests as their fathers and play ball by day
*** In the Razor House, they convince the knives not to stab them by giving them dominion over all animals
*** In cold house they shut out the cold
*** in the jaguar house they throw bones to tigers, etc
** The bat house was when they fucked up. They survived the entire night by sleeping inside their blowguns, but Hunahpu peeks a little to early
** The bat bites his head off, and it rolls to the ball court
** Xbalanque sees this and goes "fuck" and summons animals to help
** They bring a squash and Heart of Sky comes down and fashions it into a human head and gives it to the twins, where they replace Hunahpu's head with the squash
** Hunahpu's head is being used as the ball at first, before Xbalanque tricks the lords of xibalba to look away and he swaps the heads
** At this point they know there's no way to win, this game is rigged
** Because of this they know they're gonna be burnt in a stone oven as a test, and decree that their bones be thrown into the river afterwards
** The lords of xibalba build the oven,and are surprised when they freely walk in
** Their burnt bones are ground up and thrown in the river, which are then reconstructed into the brothers
** They then hatch a plan. Hunahpu and Xibalanque disguise themselves become traveling magicians!
** They perform tricks all over, killing and reviving eachother, even sacrificing to each other.
** The Xibalans hear this and summon the twins to perform for them.
** They kill and revive a dog for them, which the xabalbans demand to see it done to a person
** So the boys sacrifice and revive themselves as part of a dance
** The Xibalans ask to be sacrtificed and revived themselves, and the boys agree to show them.
** The first volunteers happen to be One Death and Seven Death, the ones who killed their father and uncle
** They kill them, and dont revive them, revealing themselves. Knowing they fucked up, they surrender.
** They find their father, still missing his head, but they put him back together but promise to remember and respect him
** Finally, the two boys ascend and become the sun and moon.
** but theres someone missing
** THATS RIGHT THE FOUR HUNDRED BOYS ARE BACK BABY
*** They become the stars in the sky, forever partying in the heavens
* THE FOURTH HUMANS
** Now that morning has come, the split of night and day now here, the Bearer, Begetter, the Makers, Modelers named Sovereign Plumed Serpent searched for another material to create the humans with.
** They find Maize, yellow corn and white corn
** Xmucane did the grinding nine times, and the wather she washed her hands with and food became human fat when worked by Bearer, Begetter, Sovereign Plumed Serpent as they worked.
** So they created the first humans, the first mother-fathers.
*** Unlike most creation myths, the first humans were not strictly male/female, but both at once, though they looked male
** The people were created in the following order
*** Jaguar Quitze
*** Jaguar Night
*** Not Right Now
*** Dark jaguar
** These first humans were good. Too good. Not only did they talk and made words unlike the monkeys, looked and listened, and they walked and worked.
** However they werent just successful. They were too successful. They saw everything perfectly, they could see everything without obstruction, and they could knew everything at once.
** They thanked the Maker, Modeler, even as they knew everything. Despite that this didn't sit rigt with the gods
** They feared they would become as great as gods. Unless they procreate at the sowing and the dawning, unless they increase
** So then they decided to take them apart a little, weakening them, and with it they lost the knowledge of everything.
** The gods now needed to make sure they could procreatem so they created wives for them, and the four original humans were immediately smitten, suddenly seeming as though they were coming alive
** Their wives were
*** Red Sea Turtle
*** Prawn House
*** Water Hummingbird
*** Macaw House
** They went off, creating all the tribes of the world, uncluding the Quiche people, and continued to worship and praise the gods as they were meant to.
