#+title: Hero Twins
* The hero twins v.s. the great pretenders
** Seven Macaw
*** 1: Hunahpu and Xbalanque are two twin gods and heros to the quinche people
*** They are an example of the Hero Twins of the north and south americas
*** 2: They hear someone spreading some absolute bullshit
*** There is a god named =Seven Mcaw= and he is going around bragging about how great he is
**** His teeth are incrusted with glittering jewels, so bright that he claims he is the sun and the moon, providing light to the (flooded) humanity
***** While there is the sun-moon in the sky, it's clouded over
**** ="I am great. My place is now higher than that of the human work, human design. I am their sun and I am their light, and I am also their months".=
**** Now these are some fake shit
*** Now Hanapu and Xbalanque can't be having that, they are good boys
*** 3: The boys find him eating in his tree and try to kill him with a blowgun, shooting him in the jaw and shattering his teeth
*** This, rightly, pisses him the hell off
*** So in the ensuing fight, he ends up rips off Hanahpu's arm and takes it home
*** 4: Hunahpu and Xbalanque go home and their grandparents are shocked to see him missing a whole ass arm
*** As any grandparents would, they decide to go deal with Seven Macaw themselves
*** 5: At home, Seven Mcaw in pain, teeth loose and jaw broken, he needs a dentist
*** 6: Seven Macaw is visited by the grandparents, who offer to help ease his pain. They brought two young boys who seem a little familiar...
*** Seven Macaw Agrees to the DIY dentistry, and they replace his jeweled teeth with maize kernels and remove all of his piercings from his face
*** When theyre done, he looks in the mirror and, heart broken, he just drops dead
**** What a drama queen
** Xipacna
*** One day, the gods of alcoholic drink who have the best name: The Four Hundred Boys, asked Seven Macaw's eldest son, A Crocodile-shaped god Xipacna, to help them build a house
**** You'd think 400 boys could do it, but I'm guessing they were to busy partying
*** As Xipacna worked, they were also shocked at how proud and arrogant he was too, so the four hundred boys decide to kill him
*** The plan backfires, and Xipacna ends up knocking down the house kill the fourhundred boys!
**** That monster!
*** Hunahpu and Xbalanque hear about this and they create fake and delicious looking crab, tucking it in a crevice in a canyon
*** They go to Xipacna and tell him what a great and tasty looking crab they found, but they weren't nearly as /amazing/ and /awesome/ as xipacna so they couldn't catch it
*** Xipacna just so happened to be starving, so he went to the canyon, found the cave, and gets stuck in the crevice. Eventualy, he turns to stone, dying
** Earthquake
*** This time, Hunahpu and Xipacna are visited by Hurricane, Newborn Thunderbolt, and Sudden Thunderbolt (Heart of Sky) and tell him Sevemn Macaw's youngest son is going around bragging about how great /he/ is, how he's even /better/ than the sun
*** The boys convince him to travel with them, and along the way they make a delicious smelling meal of some birds they hunted.
*** Unbeknowst to Earthquake, this is a dinner most /fowl/ and one of the birds is coated with gypsum. He eats the bird, and he Gypsum hardens inside him, paralyzing him so the boys can bury him.
** With that, the boys have helped prepare earth for the coming of the successful human race......
*** WAIT, I DIDN'T EXPLAIN WHERE THEY COME FROM
* One Hunahpu and Seven Hunahpu in Xibalba
** Yes, you heard that right. Let me explain
** One Hunahpu an Seven Hunahpu are twins and two of the parents of Hunahpu and Xibalanque.
*** Yes, I said /two/ of the parents. This will make sense soon
**
